service: movierec-backend

frameworkVersion: '^4.0.0'

# Custom CORS configuration for consistent setup

# Package configuration to reduce deployment size
package:
  patterns:
    - '!lambda-functions/**/node_modules/**'
    - '!node_modules/**'
    - '!.git/**'
    - '!README.md'
    - '!.env'
    - '!package-lock.json'
    - '!tests/**'
    - '!scripts/**'
    - '!public/**'
    - '!src/**'
    - '!.vscode/**'
    - '!infrastructure/**'
    - '!mcp-servers/**'
    - '!undefined/**'
    - '!*.md'
    - '!jest.config.js'
    - '!postcss.config.js'
    - '!tailwind.config.js'
    - '!webpack.config.js'
    - '!dev.js'
    - '!movierec.code-workspace'

layers:
  awsSdkLayer:
    path: lambda-layers/aws-sdk-layer
    name: ${self:provider.stage}-aws-sdk-layer
    description: AWS SDK v3 and JWT verification dependencies
    compatibleRuntimes:
      - nodejs18.x
    retain: false

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1 # Ensure this matches your deployed region
  stage: prod
  environment:
    USER_POOL_ID: ${env:REACT_APP_COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:REACT_APP_COGNITO_CLIENT_ID}
    USER_PREFERENCES_TABLE: UserPreferences
    RECOMMENDATIONS_CACHE_TABLE: MovieRecCache
    USER_FAVORITES_TABLE: Favourites
    USER_WATCHLIST_TABLE: Watchlist
    TMDB_API_KEY: ${env:REACT_APP_TMDB_API_KEY} # Ensure TMDB_API_KEY is set in your environment
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/UserPreferences"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/MovieRecCache"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/Favourites"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/Watchlist"

plugins:
  - serverless-offline
  # - serverless-dynamodb-local  # Temporarily disabled due to Java dependency
  - enkonix-serverless-dotenv-plugin

custom:
  corsConfig:
    origin: "https://www.movierec.net,http://localhost:3000"
    headers:
      - Content-Type
      - Authorization
      - X-Amz-Date
      - X-Api-Key
      - X-Amz-Security-Token
      - Accept
      - Origin
      - X-Requested-With
    allowCredentials: true
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
  serverless-offline:
    httpPort: 3001
    lambdaPort: 3002
    noAuth: true
    ignoreJWTSignature: true
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    stages:
      - dev
    migration:
      dir: offline/migrations
  #     - dev
  #   tables:
  #     - UserPreferences
  #     - MovieRecCache
  #     - Favourites
  #     - Watchlist

functions:
  signin:
    handler: lambda-functions/signin/index.handler
    layers:
      - { Ref: AwsSdkLayerLambdaLayer }
    events:
      - http:
          path: auth/signin
          method: post
          cors: ${self:custom.corsConfig}

  signup:
    handler: lambda-functions/SignupHandler/index.handler
    layers:
      - { Ref: AwsSdkLayerLambdaLayer }
    events:
      - http:
          path: auth/signup
          method: post
          cors: ${self:custom.corsConfig}

  refreshToken:
    handler: lambda-functions/RefreshTokenLambda/index.handler
    layers:
      - { Ref: AwsSdkLayerLambdaLayer }
    events:
      - http:
          path: auth/refresh
          method: post
          cors: ${self:custom.corsConfig}

  userPreferences:
    handler: lambda-functions/UserPreferencesFunction/index.handler
    layers:
      - { Ref: AwsSdkLayerLambdaLayer }
    events:
      - http:
          path: user/preferences
          method: get
          cors: ${self:custom.corsConfig}
      - http:
          path: user/preferences
          method: post
          cors: ${self:custom.corsConfig}

  favourites:
    handler: lambda-functions/FavouritesFunction/index.handler
    layers:
      - { Ref: AwsSdkLayerLambdaLayer }
    events:
      - http:
          path: user/favourites
          method: get
          cors: ${self:custom.corsConfig}
      - http:
          path: user/favourites
          method: post
          cors: ${self:custom.corsConfig}
      - http:
          path: user/favourites
          method: delete
          cors: ${self:custom.corsConfig}

  watchlist:
    handler: lambda-functions/watchlist/index.handler
    layers:
      - { Ref: AwsSdkLayerLambdaLayer }
    events:
      - http:
          path: user/watchlist
          method: get
          cors: ${self:custom.corsConfig}
      - http:
          path: user/watchlist
          method: post
          cors: ${self:custom.corsConfig}
      - http:
          path: user/watchlist
          method: delete
          cors: ${self:custom.corsConfig}

  userStats:
    handler: lambda-functions/UserStatsFunction/index.handler
    layers:
      - { Ref: AwsSdkLayerLambdaLayer }
    events:
      - http:
          path: user/stats/{action}
          method: get
          cors: ${self:custom.corsConfig}
      - http:
          path: user/stats/{action}
          method: post
          cors: ${self:custom.corsConfig}

  recommendations:
    handler: lambda-functions/MovieRecPersonalizedApiHandler/index.handler
    layers:
      - { Ref: AwsSdkLayerLambdaLayer }
    events:
      - http:
          path: recommendations
          method: get
          cors: ${self:custom.corsConfig}

  mediaCache:
    handler: lambda-functions/MediaCache/index.handler
    layers:
      - { Ref: AwsSdkLayerLambdaLayer }
    events:
      - http:
          path: media
          method: get
          cors: ${self:custom.corsConfig}

# DynamoDB tables are managed by CDK infrastructure
